apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: wordpress
data:
  wordpress.conf: |
    server {
      listen 80;

      root /var/www/html/wordpress;
      index index.php index.html index.htm;
      
      server_name localhost:30004;

      location / {
        try_files $uri $uri/ /index.php?$args;
      }

      location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }
    }
