apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sa
  namespace: wordpress
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
